/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWebhookDocsRouteImport } from './routes/_app.webhook-docs'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppStatementsRouteImport } from './routes/_app.statements'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPayBillsRouteImport } from './routes/_app.pay-bills'
import { Route as AppMobileRechargeRouteImport } from './routes/_app.mobile-recharge'
import { Route as AppLoansRouteImport } from './routes/_app.loans'
import { Route as AppInvestmentsRouteImport } from './routes/_app.investments'
import { Route as AppInsuranceRouteImport } from './routes/_app.insurance'
import { Route as AppGovernmentSchemesRouteImport } from './routes/_app.government-schemes'
import { Route as AppFundTransferRouteImport } from './routes/_app.fund-transfer'
import { Route as AppDepositsRouteImport } from './routes/_app.deposits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCardsRouteImport } from './routes/_app.cards'
import { Route as AppBeneficiariesRouteImport } from './routes/_app.beneficiaries'
import { Route as AppBankStatementRouteImport } from './routes/_app.bank-statement'
import { Route as AppAccountsRouteImport } from './routes/_app.accounts'
import { Route as AppAccountDetailsRouteImport } from './routes/_app.account-details'
import { Route as ApiPublicSmsWebhookRouteImport } from './routes/api/public/sms-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebhookDocsRoute = AppWebhookDocsRouteImport.update({
  id: '/webhook-docs',
  path: '/webhook-docs',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementsRoute = AppStatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPayBillsRoute = AppPayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => AppRoute,
} as any)
const AppMobileRechargeRoute = AppMobileRechargeRouteImport.update({
  id: '/mobile-recharge',
  path: '/mobile-recharge',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestmentsRoute = AppInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AppRoute,
} as any)
const AppInsuranceRoute = AppInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AppRoute,
} as any)
const AppGovernmentSchemesRoute = AppGovernmentSchemesRouteImport.update({
  id: '/government-schemes',
  path: '/government-schemes',
  getParentRoute: () => AppRoute,
} as any)
const AppFundTransferRoute = AppFundTransferRouteImport.update({
  id: '/fund-transfer',
  path: '/fund-transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsRoute = AppDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppBeneficiariesRoute = AppBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => AppRoute,
} as any)
const AppBankStatementRoute = AppBankStatementRouteImport.update({
  id: '/bank-statement',
  path: '/bank-statement',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountDetailsRoute = AppAccountDetailsRouteImport.update({
  id: '/account-details',
  path: '/account-details',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSmsWebhookRoute = ApiPublicSmsWebhookRouteImport.update({
  id: '/api/public/sms-webhook',
  path: '/api/public/sms-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/account-details': typeof AppAccountDetailsRoute
  '/accounts': typeof AppAccountsRoute
  '/bank-statement': typeof AppBankStatementRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/fund-transfer': typeof AppFundTransferRoute
  '/government-schemes': typeof AppGovernmentSchemesRoute
  '/insurance': typeof AppInsuranceRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/mobile-recharge': typeof AppMobileRechargeRoute
  '/pay-bills': typeof AppPayBillsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRoute
  '/webhook-docs': typeof AppWebhookDocsRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/account-details': typeof AppAccountDetailsRoute
  '/accounts': typeof AppAccountsRoute
  '/bank-statement': typeof AppBankStatementRoute
  '/beneficiaries': typeof AppBeneficiariesRoute
  '/cards': typeof AppCardsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deposits': typeof AppDepositsRoute
  '/fund-transfer': typeof AppFundTransferRoute
  '/government-schemes': typeof AppGovernmentSchemesRoute
  '/insurance': typeof AppInsuranceRoute
  '/investments': typeof AppInvestmentsRoute
  '/loans': typeof AppLoansRoute
  '/mobile-recharge': typeof AppMobileRechargeRoute
  '/pay-bills': typeof AppPayBillsRoute
  '/settings': typeof AppSettingsRoute
  '/statements': typeof AppStatementsRoute
  '/support': typeof AppSupportRoute
  '/transactions': typeof AppTransactionsRoute
  '/webhook-docs': typeof AppWebhookDocsRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/disclaimer': typeof DisclaimerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/_app/account-details': typeof AppAccountDetailsRoute
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/bank-statement': typeof AppBankStatementRoute
  '/_app/beneficiaries': typeof AppBeneficiariesRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deposits': typeof AppDepositsRoute
  '/_app/fund-transfer': typeof AppFundTransferRoute
  '/_app/government-schemes': typeof AppGovernmentSchemesRoute
  '/_app/insurance': typeof AppInsuranceRoute
  '/_app/investments': typeof AppInvestmentsRoute
  '/_app/loans': typeof AppLoansRoute
  '/_app/mobile-recharge': typeof AppMobileRechargeRoute
  '/_app/pay-bills': typeof AppPayBillsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/statements': typeof AppStatementsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/webhook-docs': typeof AppWebhookDocsRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/account-details'
    | '/accounts'
    | '/bank-statement'
    | '/beneficiaries'
    | '/cards'
    | '/dashboard'
    | '/deposits'
    | '/fund-transfer'
    | '/government-schemes'
    | '/insurance'
    | '/investments'
    | '/loans'
    | '/mobile-recharge'
    | '/pay-bills'
    | '/settings'
    | '/statements'
    | '/support'
    | '/transactions'
    | '/webhook-docs'
    | '/api/public/sms-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/account-details'
    | '/accounts'
    | '/bank-statement'
    | '/beneficiaries'
    | '/cards'
    | '/dashboard'
    | '/deposits'
    | '/fund-transfer'
    | '/government-schemes'
    | '/insurance'
    | '/investments'
    | '/loans'
    | '/mobile-recharge'
    | '/pay-bills'
    | '/settings'
    | '/statements'
    | '/support'
    | '/transactions'
    | '/webhook-docs'
    | '/api/public/sms-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/disclaimer'
    | '/forgot-password'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/_app/account-details'
    | '/_app/accounts'
    | '/_app/bank-statement'
    | '/_app/beneficiaries'
    | '/_app/cards'
    | '/_app/dashboard'
    | '/_app/deposits'
    | '/_app/fund-transfer'
    | '/_app/government-schemes'
    | '/_app/insurance'
    | '/_app/investments'
    | '/_app/loans'
    | '/_app/mobile-recharge'
    | '/_app/pay-bills'
    | '/_app/settings'
    | '/_app/statements'
    | '/_app/support'
    | '/_app/transactions'
    | '/_app/webhook-docs'
    | '/api/public/sms-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DisclaimerRoute: typeof DisclaimerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  ApiPublicSmsWebhookRoute: typeof ApiPublicSmsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/webhook-docs': {
      id: '/_app/webhook-docs'
      path: '/webhook-docs'
      fullPath: '/webhook-docs'
      preLoaderRoute: typeof AppWebhookDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statements': {
      id: '/_app/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof AppStatementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pay-bills': {
      id: '/_app/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof AppPayBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mobile-recharge': {
      id: '/_app/mobile-recharge'
      path: '/mobile-recharge'
      fullPath: '/mobile-recharge'
      preLoaderRoute: typeof AppMobileRechargeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans': {
      id: '/_app/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investments': {
      id: '/_app/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AppInvestmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance': {
      id: '/_app/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof AppInsuranceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/government-schemes': {
      id: '/_app/government-schemes'
      path: '/government-schemes'
      fullPath: '/government-schemes'
      preLoaderRoute: typeof AppGovernmentSchemesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fund-transfer': {
      id: '/_app/fund-transfer'
      path: '/fund-transfer'
      fullPath: '/fund-transfer'
      preLoaderRoute: typeof AppFundTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits': {
      id: '/_app/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof AppDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beneficiaries': {
      id: '/_app/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof AppBeneficiariesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank-statement': {
      id: '/_app/bank-statement'
      path: '/bank-statement'
      fullPath: '/bank-statement'
      preLoaderRoute: typeof AppBankStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account-details': {
      id: '/_app/account-details'
      path: '/account-details'
      fullPath: '/account-details'
      preLoaderRoute: typeof AppAccountDetailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sms-webhook': {
      id: '/api/public/sms-webhook'
      path: '/api/public/sms-webhook'
      fullPath: '/api/public/sms-webhook'
      preLoaderRoute: typeof ApiPublicSmsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountDetailsRoute: typeof AppAccountDetailsRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppBankStatementRoute: typeof AppBankStatementRoute
  AppBeneficiariesRoute: typeof AppBeneficiariesRoute
  AppCardsRoute: typeof AppCardsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepositsRoute: typeof AppDepositsRoute
  AppFundTransferRoute: typeof AppFundTransferRoute
  AppGovernmentSchemesRoute: typeof AppGovernmentSchemesRoute
  AppInsuranceRoute: typeof AppInsuranceRoute
  AppInvestmentsRoute: typeof AppInvestmentsRoute
  AppLoansRoute: typeof AppLoansRoute
  AppMobileRechargeRoute: typeof AppMobileRechargeRoute
  AppPayBillsRoute: typeof AppPayBillsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatementsRoute: typeof AppStatementsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWebhookDocsRoute: typeof AppWebhookDocsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountDetailsRoute: AppAccountDetailsRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppBankStatementRoute: AppBankStatementRoute,
  AppBeneficiariesRoute: AppBeneficiariesRoute,
  AppCardsRoute: AppCardsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepositsRoute: AppDepositsRoute,
  AppFundTransferRoute: AppFundTransferRoute,
  AppGovernmentSchemesRoute: AppGovernmentSchemesRoute,
  AppInsuranceRoute: AppInsuranceRoute,
  AppInvestmentsRoute: AppInvestmentsRoute,
  AppLoansRoute: AppLoansRoute,
  AppMobileRechargeRoute: AppMobileRechargeRoute,
  AppPayBillsRoute: AppPayBillsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatementsRoute: AppStatementsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWebhookDocsRoute: AppWebhookDocsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DisclaimerRoute: DisclaimerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  ApiPublicSmsWebhookRoute: ApiPublicSmsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
